"""
    OpInfo

Cached metadata for a single local operator on a given site.

Fields:
- `matrix`: dense matrix representation of the operator.
- `is_fermionic`: whether the operator has an odd fermion parity.
- `qn_flux`: the quantum-number flux carried by the operator.
"""
struct OpInfo
  matrix::Matrix
  is_fermionic::Bool
  qn_flux::QN
end

"""
    OpInfo(local_op::Op, site::Index) -> OpInfo

Construct an `OpInfo` by evaluating `local_op` on `site`, caching its dense
matrix, fermionic character, and QN flux.

If `flux(op(...))` is `nothing`, the stored flux defaults to `QN()`.
"""
function OpInfo(local_op::Op, site::Index)
  tensor = op(site, ITensors.which_op(local_op); ITensors.params(local_op)...)
  is_fermionic = has_fermion_string(ITensors.name(local_op), site)
  qn_flux = flux(tensor)

  return OpInfo(copy(array(tensor)), is_fermionic, isnothing(qn_flux) ? QN() : qn_flux)
end

"""
    OpCacheVec

A type alias for a map from site index, and operator index to `OpInfo`.
"""
OpCacheVec = Vector{Vector{OpInfo}}

"""
    to_OpCacheVec(sites::Vector{<:Index}, ops::OpCacheVec) -> OpCacheVec

Validate and return a precomputed operator cache.

The length of sites must match the length of ops and the first operator
for every site must be the identity.
"""
function to_OpCacheVec(sites::Vector{<:Index}, ops::OpCacheVec)::OpCacheVec
  length(sites) != length(ops) &&
    error("Mismatch in the number of sites in `sites` and `ops`.")
  any(ops[i][1].matrix != I for i in 1:length(sites)) &&
    error("The first operator on each site must be the identity.")
  return ops
end

"""
    to_OpCacheVec(sites::Vector{<:Index}, ops::Vector{Vector{String}}) -> OpCacheVec

Build an `OpCacheVec` from operator names for each site.

`ops[n]` is the ordered list of operator names available on site `n`, and the
first entry for every site must be `"I"`, which is reserved for the identity.
"""
function to_OpCacheVec(sites::Vector{<:Index}, ops::Vector{Vector{String}})::OpCacheVec
  length(sites) != length(ops) &&
    error("Mismatch in the number of sites in `sites` and `ops`.")
  any(ops[i][1] != "I" for i in 1:length(sites)) &&
    error("The first operator on each site must be the identity.")
  return [[OpInfo(ITensors.Op(op, n), sites[n]) for op in ops[n]] for n in 1:length(sites)]
end

"""
    to_OpCacheVec(sites::Vector{<:Index}, ::Nothing) -> Nothing

Pass through `nothing` for call sites where an optional operator cache is
allowed.
"""
function to_OpCacheVec(sites::Vector{<:Index}, ::Nothing)::Nothing
  return nothing
end

"""
    OpID{Ti}

Compact identifier for an operator stored in an `OpCacheVec`.

Type Parameters
- `Ti`: The integer type used to store both the operator ID and site.

Fields:
- `id`: index of the operator within the cache for site `n`.
- `n`: site number on which the operator acts.

The zero value `OpID(0, 0)` is used internally as padding for unused slots in
fixed-width storage.
"""
struct OpID{Ti}
  id::Ti
  n::Ti
end

Base.zero(::OpID{Ti}) where {Ti} = OpID{Ti}(0, 0)

Base.isless(op1::OpID, op2::OpID) = (op1.n, op1.id) < (op2.n, op2.id)

"""
    sort_fermion_perm!(ops::AbstractVector{<:OpID}, op_cache_vec::OpCacheVec) -> Int

Sort `ops` in place by site index and return the fermionic sign generated by the
permutation.

Whenever two fermionic operators are swapped past one another, the returned sign
is multiplied by `-1`. Non-fermionic swaps do not affect the sign.
"""
function sort_fermion_perm!(ops::AbstractVector{<:OpID}, op_cache_vec::OpCacheVec)::Int
  sign = +1
  for i in 2:length(ops)
    cur_op_is_fermionic = op_cache_vec[ops[i].n][ops[i].id].is_fermionic
    while i > 1 && ops[i].n < ops[i - 1].n
      if cur_op_is_fermionic && op_cache_vec[ops[i - 1].n][ops[i - 1].id].is_fermionic
        sign = -sign
      end

      ops[i - 1], ops[i] = ops[i], ops[i - 1]
      i -= 1
    end
  end

  return sign
end

"""
    OpIDSum{N,C,Ti}

Compact representation of an operator sum whose terms are stored as fixed-width
tuples of `OpID` values together with scalar coefficients.

Type Parameters:
- `N`: The maximum number of onsite operators per term, i.e. the weight of the operator.
- `C`: The scalar coefficient type.
- `Ti`: The integer type used to identify both an operator and the sites.

Fields:
- `_data`: Holds all the terms in the operator.
- `terms`: A view of `_data` that allows for modifying the operators of each term.
- `scalars`: A vector containing the coefficient for each term.
- `num_terms`: An atomic holding the current number of terms in the operator.
- `op_cache_vec`: The cache that defines the operators acting on each site.
- `abs_tol`: When adding terms to the operator, terms with coefficients smaller
  than this are dropped.
- `modify!`: A function which can modify a term in-place after calling `add!`.

Note (corbett5):
A compile-time maximum weight (i.e. `N`) is necessary to limit allocations here and
in other parts of the code. The janky relationship between `_data` and `terms` is
a result of this as well, since Julia seemed unable to optimize away the allocations
associated with StaticArrays.MVector.
"""
mutable struct OpIDSum{N,C,Ti}
  _data::Vector{NTuple{N,OpID{Ti}}}
  terms::Base.ReinterpretArray{
    OpID{Ti},2,NTuple{N,OpID{Ti}},Vector{NTuple{N,OpID{Ti}}},true
  }
  scalars::Vector{C}
  num_terms::Threads.Atomic{Int}
  op_cache_vec::OpCacheVec
  abs_tol::Float64
  modify!::FunctionWrappers.FunctionWrapper{
    C,
    Tuple{
      SubArray{
        OpID{Ti},
        1,
        Base.ReinterpretArray{
          OpID{Ti},2,NTuple{N,OpID{Ti}},Vector{NTuple{N,OpID{Ti}}},true
        },
        Tuple{UnitRange{Int64},Int64},
        false,
      },
    },
  }
end

"""
    OpIDSum{N,C,Ti}(max_terms, op_cache_vec, f; abs_tol=0) -> OpIDSum{N,C,Ti}

Create an empty `OpIDSum` with capacity for `max_terms` terms.

`f` is a term-rewriting callback that is applied to each nonzero stored term
just after the operators have been sorted by site. Its return value rescales the
term coefficient. Terms with `abs(scalar) <= abs_tol` are ignored when added.
"""
function OpIDSum{N,C,Ti}(
  max_terms::Int, op_cache_vec::OpCacheVec, f::Function; abs_tol::Real=0
)::OpIDSum{N,C,Ti} where {N,C,Ti}
  data = Vector{NTuple{N,OpID{Ti}}}(undef, max_terms)
  terms = reinterpret(reshape, OpID{Ti}, data)
  f_wrapped = FunctionWrappers.FunctionWrapper{
    C,
    Tuple{
      SubArray{
        OpID{Ti},
        1,
        Base.ReinterpretArray{
          OpID{Ti},2,NTuple{N,OpID{Ti}},Vector{NTuple{N,OpID{Ti}}},true
        },
        Tuple{UnitRange{Int64},Int64},
        false,
      },
    },
  }(
    f
  )
  return OpIDSum(
    data,
    terms,
    Vector{C}(undef, max_terms),
    Threads.Atomic{Int}(0),
    op_cache_vec,
    Float64(abs_tol),
    f_wrapped,
  )
end

"""
    OpIDSum{N,C,Ti}(max_terms, op_cache_vec; abs_tol=0) -> OpIDSum{N,C,Ti}

Create an empty `OpIDSum` with capacity for `max_terms` terms.

Terms with `abs(scalar) <= abs_tol` are ignored when added.
"""
function OpIDSum{N,C,Ti}(
  max_terms::Int, op_cache_vec::OpCacheVec; abs_tol::Real=0
)::OpIDSum{N,C,Ti} where {N,C,Ti}
  return OpIDSum{N,C,Ti}(max_terms, op_cache_vec, ops -> 1; abs_tol)
end

"""
    length(os::OpIDSum) -> Int

Return the number of terms currently stored in `os`.
"""
function Base.length(os::OpIDSum)::Int
  return os.num_terms[]
end

"""
    eachindex(os::OpIDSum) -> UnitRange{Int}

Return the valid term indices of `os`.
"""
function Base.eachindex(os::OpIDSum)::UnitRange{Int}
  return 1:length(os)
end

"""
    getindex(os::OpIDSum, i::Integer)

Return the pair `(scalar, ops)` for the `i`th term of `os`, where `ops` is a
view into the fixed-width `OpID` storage for that term.
"""
function Base.getindex(os::OpIDSum, i::Integer)
  return os.scalars[i], view(os.terms, :, i)
end

"""
    add!(os::OpIDSum, scalar::Number, ops) -> Nothing

Append a term (defined by `ops`) to `os`. This function is thread-safe.

Identity operators (`id == 1`) are removed before storage, remaining operators
are sorted by site with the appropriate fermionic permutation sign, and the
term-modification callback associated with `os` is applied. Terms below
`os.abs_tol` are skipped.
"""
function ITensorMPS.add!(os::OpIDSum, scalar::Number, ops)::Nothing
  abs(scalar) <= os.abs_tol && return nothing

  num_terms = Threads.atomic_add!(os.num_terms, 1) + 1
  num_appended = 0
  for op in ops
    op.id == 1 && continue ## Filter out identity ops

    num_appended += 1
    os.terms[num_appended, num_terms] = op
  end

  for i in (num_appended + 1):size(os.terms, 1)
    os.terms[i, num_terms] = zero(os.terms[i, num_terms])
  end

  permutation_sign = sort_fermion_perm!(
    view(os.terms, 1:num_appended, num_terms), os.op_cache_vec
  )

  scalar_modification = os.modify!(view(os.terms, 1:num_appended, num_terms))

  os.scalars[num_terms] = scalar * permutation_sign * scalar_modification

  return nothing
end

"""
    add!(os::OpIDSum, scalar::Number, ops::OpID...) -> Nothing

Vararg convenience method for `add!`.
"""
function ITensorMPS.add!(os::OpIDSum, scalar::Number, ops::OpID...)::Nothing
  return add!(os, scalar, ops)
end

"""
    determine_val_type(os::OpIDSum)

Return the numeric element type needed to represent the coefficients and cached
operator matrices in `os`.

This is `ComplexF64` if either the stored coefficients or any cached operator
matrix has nonzero imaginary part; otherwise it is `Float64`.
"""
function determine_val_type(os::OpIDSum)
  !all(isreal(scalar) for scalar in os.scalars) && return ComplexF64
  !all(isreal(op.matrix) for ops_of_site in os.op_cache_vec for op in ops_of_site) &&
    return ComplexF64
  return Float64
end

"""
    for_equal_sites(f::Function, ops::AbstractVector{<:OpID}) -> Nothing

Call `f(i, j)` for each maximal contiguous block of operators in `ops` that act
on the same site, where `i` and `j` denote the start and end of the contiguous block.

This assumes `ops` are already sorted by site, as happens after sorting terms
inside `OpIDSum`.
"""
function for_equal_sites(f::Function, ops::AbstractVector{<:OpID})::Nothing
  i = 1
  while i <= length(ops)
    j = i
    while j <= length(ops)
      (j == length(ops) || ops[i].n != ops[j + 1].n) && break
      j += 1
    end

    f(i, j)
    i = j + 1
  end

  return nothing
end

"""
    rewrite_in_operator_basis!(os::OpIDSum, basis_op_cache_vec::OpCacheVec)

Rewrite each same-site operator product in `os` into a single operator drawn
from `basis_op_cache_vec`.

For each contiguous block of operators acting on the same site, the product
matrix is matched against the supplied basis up to an overall scalar factor. The
term coefficient is updated by that factor, the block is replaced by the matched
basis operator, and the remaining slots are zeroed. An error is thrown if a
product cannot be represented by a single basis operator.
"""
@timeit function rewrite_in_operator_basis!(
  os::OpIDSum{N,C,Ti}, basis_op_cache_vec::OpCacheVec
) where {N,C,Ti}
  op_cache_vec = os.op_cache_vec

  function scale_by_first_nz!(matrix::Matrix)
    for i in eachindex(matrix)
      entry = matrix[i]
      if entry != 0
        matrix ./= entry
        return entry
      end
    end
  end

  scaled_basis_ops = Vector{Tuple{ComplexF64,Matrix{ComplexF64}}}[
    Vector{Tuple{ComplexF64,Matrix{ComplexF64}}}() for _ in eachindex(basis_op_cache_vec)
  ]
  for n in eachindex(basis_op_cache_vec)
    for op_info in basis_op_cache_vec[n]
      m = copy(op_info.matrix)
      scale = scale_by_first_nz!(m)
      push!(scaled_basis_ops[n], (scale, m))
    end
  end

  function convert_to_basis(ops::AbstractVector{OpID{Ti}})::Tuple{ComplexF64,Int}
    @assert !isempty(ops)
    n = ops[1].n
    @assert all(op.n == n for op in ops)

    if length(ops) == 1
      local_matrix = copy(op_cache_vec[n][ops[1].id].matrix)
    else
      local_matrix = prod(op_cache_vec[n][op.id].matrix for op in ops)
    end
    
    scale = scale_by_first_nz!(local_matrix)
    for (i, (basis_scale, basis_matrix)) in enumerate(scaled_basis_ops[n])
      basis_matrix == local_matrix && return scale / basis_scale, i
    end

    return 0, 0
  end

  single_op_translation = Vector{Tuple{ComplexF64,Int}}[
    Vector{Tuple{ComplexF64,Int}}() for _ in eachindex(basis_op_cache_vec)
  ]
  for n in eachindex(op_cache_vec)
    for id in eachindex(op_cache_vec[n])
      push!(single_op_translation[n], convert_to_basis([OpID{Ti}(id, n)]))
    end
  end

  for i in eachindex(os)
    scalar, ops = os[i]

    for_equal_sites(ops) do a, b
      ops[a] == zero(ops[a]) && return nothing

      if a == b
        coeff, basis_id = single_op_translation[ops[a].n][ops[a].id]
      else
        coeff, basis_id = convert_to_basis(view(ops, a:b))
      end

      if basis_id == 0
        error(
          "The following operator product cannot be simplified into a single basis operator.\n" *
          "\tOperator product = $(ops[a:b]), $ops\n",
        )
      end

      scalar *= coeff

      ops[a] = OpID{Ti}(basis_id, ops[a].n)
      for k in (a + 1):b
        ops[k] = zero(ops[k])
      end
    end

    os.scalars[i] = scalar
  end

  sort!(os.terms; dims=1, by=op -> op.n)
  os.op_cache_vec = basis_op_cache_vec

  return os
end

"""
    op_sum_to_opID_sum(os::OpSum{C}, sites::Vector{<:Index}) -> OpIDSum

Convert an ITensor `OpSum` into an `OpIDSum`.

Each distinct local operator encountered on a site is assigned an integer id and
cached in an `OpCacheVec`, with id `1` reserved for the identity. Terms are then
added to the resulting `OpIDSum` using those cached identifiers.
"""
@timeit function op_sum_to_opID_sum(os::OpSum{C}, sites::Vector{<:Index})::OpIDSum where {C}
  N = length(sites)

  ops_on_each_site = [Dict{Op,Int}(Op("I", n) => 1) for n in 1:N]
  op_cache_vec = [[OpInfo(Op("I", n), sites[n])] for n in 1:N]

  ## If there is only a single op per term then there actually winds up being a weird
  ## error when using reinterpret(reshape, ...) later on. This is the easiest way to fix it.
  max_ops_per_term = max(2, maximum(length, ITensors.terms(os)))

  opID_sum = OpIDSum{max_ops_per_term,C,Int}(length(os), op_cache_vec)

  opID_term = Vector{OpID{Int}}()
  for term in os
    resize!(opID_term, 0)
    for op in ITensors.terms(term)
      op.which_op == "I" && continue

      n = ITensors.site(op)

      if op ∉ keys(ops_on_each_site[n])
        ops_on_each_site[n][op] = length(ops_on_each_site[n]) + 1
        push!(op_cache_vec[n], OpInfo(op, sites[n]))
      end

      opID = ops_on_each_site[n][op]
      push!(opID_term, OpID(opID, n))
    end

    add!(opID_sum, ITensors.coefficient(term), opID_term)
  end

  return opID_sum
end

"""
    check_os_for_errors(os::OpIDSum) -> Nothing

Validate structural assumptions for `os`.

This checks that, within every term, operators are sorted by site, at most one
operator acts on each site, all terms carry the same total QN flux, and
every term has even fermion parity.
"""
@timeit function check_os_for_errors(os::OpIDSum)::Nothing
  flux_of_first_term = nothing
  for i in eachindex(os)
    _, ops = os[i]

    flux = QN()
    fermion_parity = 0
    for j in eachindex(ops)
      opj = ops[j]
      opj == zero(opj) && continue

      flux += os.op_cache_vec[opj.n][opj.id].qn_flux
      fermion_parity += os.op_cache_vec[opj.n][opj.id].is_fermionic

      if j < length(ops)
        ops[j + 1] == zero(ops[j + 1]) && continue
        ops[j].n > ops[j + 1].n && error("The operators are not sorted by site: $ops")
        ops[j].n == ops[j + 1].n &&
          error("A site has more than one operator acting on it in a term: $ops")
      end
    end

    if isnothing(flux_of_first_term)
      flux_of_first_term = flux
    else
      flux != flux_of_first_term && error(
        "Inconsistent flux found!\n" *
        "  Term 1 has a flux of $flux_of_first_term\n" *
        "  Term $i has a flux of $flux"
      )
    end

    mod(fermion_parity, 2) != 0 && error("Odd parity fermion terms not supported: $ops")
  end
end

"""
    prepare_opID_sum!(os::OpIDSum, basis_op_cache_vec::Union{Nothing,OpCacheVec})

Apply optional preprocessing to `os` before MPO construction.

Currently this rewrites terms into `basis_op_cache_vec` when a basis cache is
provided and otherwise leaves `os` unchanged.
"""
@timeit function prepare_opID_sum!(
  os::OpIDSum, basis_op_cache_vec::Union{Nothing,OpCacheVec}
)
  if !isnothing(basis_op_cache_vec)
    rewrite_in_operator_basis!(os, basis_op_cache_vec)
  end
end
